name: Terraform Backend Workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Test_and_Update:
    runs-on: ubuntu-latest
    env: 
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:

    - uses: actions/checkout@v3

    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Add requirements
      run: python3.11 -m pip install boto3 moto[dynamodb]

    - name: List installed packages
      run: pip freeze

    - name: Unit Test
      run: python3.11 -m unittest visitor_call.test_function

    - name: Configure AWS Credentials for Github Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve


